version: "3.9"
services:
  web:
    image: samavgn02/docker-frontend:da066d6
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    image: null/docker-backend:1345678
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
