version: "3.8"
services:
  web:
    image: samavgn02/docker-frontend:8eda06e
    depends_on:
      - api
    ports:
      - "3000:3000"
    env_file:
      - .env-frontend
    networks:
      - network-backend
  api:
    image: samavgn02/docker-backend:ad26919
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    env_file:
      - .env-backend
    networks: 
      - network-backend
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db
    env_file:
      - .env-db
    networks:
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
